--- # Settings to be used by iterative algorithm computing material properties from the strain data

# Location of strain data:
StrainDataFilePath:
  - 'data\Strain.xlsx'  # from full-field measurement
  -

# Iteration settiongs:
itMax: 50     # maximum number of iterations
tol: 1e-09    # desired tolerance

# Additional files for benchmarking:
StressDataFilePath: 'data\Stress.xlsx'
DisplDataFilePath: 'data\Displacement.xlsx'
RndMatPropPath: 'data\021050_344\MatProperties_021050_344.mat'
... # Ends .yml file
